// <auto-generated />
using System;
using Kura.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Kura.Infrastructure.Migrations
{
    [DbContext(typeof(KuraDbContext))]
    [Migration("20260501234733_AdicionaSenhaClinica")]
    partial class AdicionaSenhaClinica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kura.Domain.Entities.AlertaTemperatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_ALERTA_TEMPERATURA.NEXTVAL");

                    b.Property<string>("DsMensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsTipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_TIPO_ALERTA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdLeituraTemperatura")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA_TEMPERATURA");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.Property<string>("StResolvido")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_RESOLVIDO");

                    b.Property<decimal>("VlLimite")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_LIMITE");

                    b.HasKey("Id");

                    b.HasIndex("IdLeituraTemperatura");

                    b.ToTable("ALERTA_TEMPERATURA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_CLINICA.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsEndereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("DsSenha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_SENHA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmClinica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_CLINICA");

                    b.Property<string>("NrCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("NrCnpj")
                        .IsUnique();

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_DISPOSITIVO_IOT.NEXTVAL");

                    b.Property<string>("CdDispositivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_DISPOSITIVO");

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("DsLocalizacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("CdDispositivo")
                        .IsUnique();

                    b.HasIndex("IdClinica");

                    b.ToTable("DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_DOCUMENTO.NEXTVAL");

                    b.Property<string>("DsCaminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_CAMINHO");

                    b.Property<string>("DsTipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_TIPO_MIME");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmArquivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ARQUIVO");

                    b.Property<long>("NrTamanhoBytes")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_TAMANHO_BYTES");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Especie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_ESPECIE.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmEspecie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ESPECIE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.ToTable("ESPECIE", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.EventoClinico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_EVENTO_CLINICO.NEXTVAL");

                    b.Property<string>("DsObservacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EVENTO");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<long>("IdTipoEvento")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_EVENTO");

                    b.Property<long>("IdVeterinario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdTipoEvento");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("EVENTO_CLINICO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Exame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_EXAME.NEXTVAL");

                    b.Property<string>("DsResultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_RESULTADO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtRealizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REALIZACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmExame")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_EXAME");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("EXAME", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.LeituraTemperatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_LEITURA_TEMPERATURA.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdDispositivoIot")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO_IOT");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.Property<decimal>("VlTemperatura")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_TEMPERATURA");

                    b.Property<decimal?>("VlUmidade")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_UMIDADE");

                    b.HasKey("Id");

                    b.HasIndex("IdDispositivoIot");

                    b.ToTable("LEITURA_TEMPERATURA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.LogErro", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOG")
                        .HasDefaultValueSql("SEQ_LOG_ERRO.NEXTVAL");

                    b.Property<string>("DsEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_ENDPOINT");

                    b.Property<string>("DsMensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsMetodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_METODO");

                    b.Property<string>("DsStackTrace")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_STACK_TRACE");

                    b.Property<DateTime>("DtOcorrencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_OCORRENCIA");

                    b.Property<int>("NrStatusCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_STATUS_CODE");

                    b.HasKey("IdLog");

                    b.ToTable("LOG_ERRO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Medicamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_MEDICAMENTO.NEXTVAL");

                    b.Property<string>("DsApresentacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_APRESENTACAO");

                    b.Property<string>("DsPrincipioAtivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_PRINCIPIO_ATIVO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmMedicamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_MEDICAMENTO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.ToTable("MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_NOTIFICACAO.NEXTVAL");

                    b.Property<string>("DsMensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_TITULO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long?>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<long?>("IdVeterinario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.Property<string>("StLida")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_LIDA");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_PET.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<long>("IdEspecie")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<long>("IdRaca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RACA");

                    b.Property<long?>("IdVeterinarioResp")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO_RESP");

                    b.Property<string>("NmPet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_PET");

                    b.Property<string>("SgPorte")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SG_PORTE");

                    b.Property<string>("SgSexo")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SG_SEXO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdRaca");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Prescricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_PRESCRICAO.NEXTVAL");

                    b.Property<string>("DsPosologia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_POSOLOGIA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<long>("IdMedicamento")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MEDICAMENTO");

                    b.Property<int>("NrDuracaoDias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_DURACAO_DIAS");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.HasIndex("IdMedicamento");

                    b.ToTable("PRESCRICAO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Raca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_RACA.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEspecie")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<string>("NmRaca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_RACA");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_TIPO_EVENTO.NEXTVAL");

                    b.Property<string>("CdTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_TIPO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_TIPO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("CdTipo")
                        .IsUnique();

                    b.ToTable("TIPO_EVENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Tutor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_TUTOR.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmTutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_TUTOR");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("NrCpf")
                        .IsUnique();

                    b.ToTable("TUTOR", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.TutorPet", b =>
                {
                    b.Property<long>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("DsVinculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_VINCULO");

                    b.Property<DateTime>("DtVinculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_VINCULO");

                    b.Property<string>("StPrincipal")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_PRINCIPAL");

                    b.HasKey("IdTutor", "IdPet");

                    b.HasIndex("IdPet");

                    b.ToTable("TUTOR_PET", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Vacina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_VACINA.NEXTVAL");

                    b.Property<string>("DsFabricante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_FABRICANTE");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtProximaDose")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROXIMA_DOSE");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmVacina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_VACINA");

                    b.Property<string>("NrLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NR_LOTE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("VACINA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Veterinario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SEQ_VETERINARIO.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("NmVeterinario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_VETERINARIO");

                    b.Property<string>("NrCrmv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_CRMV");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica");

                    b.HasIndex("NrCrmv")
                        .IsUnique();

                    b.ToTable("VETERINARIO", (string)null);
                });

            modelBuilder.Entity("Kura.Infrastructure.Persistence.ReadModels.TimelineItem", b =>
                {
                    b.Property<string>("DsObservacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DtEvento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmPet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmVeterinario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.ToTable((string)null);

                    b.ToView("VW_TIMELINE_PET", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.AlertaTemperatura", b =>
                {
                    b.HasOne("Kura.Domain.Entities.LeituraTemperatura", "LeituraTemperatura")
                        .WithMany()
                        .HasForeignKey("IdLeituraTemperatura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeituraTemperatura");
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.EventoClinico", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("IdTipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("TipoEvento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Exame", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.LeituraTemperatura", b =>
                {
                    b.HasOne("Kura.Domain.Entities.DispositivoIot", "DispositivoIot")
                        .WithMany("Leituras")
                        .HasForeignKey("IdDispositivoIot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kura.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tutor");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("IdRaca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Prescricao", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Raca", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Kura.Domain.Entities.TutorPet", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Pet", "Pet")
                        .WithMany("TutorPets")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany("TutorPets")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Vacina", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Veterinario", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.Navigation("TutorPets");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("TutorPets");
                });
#pragma warning restore 612, 618
        }
    }
}
